disabled = false
languageCode = "en"
languageName = "English"
weight = 1
title = "AskBlueCat"

[params]
displayName = "EN"
isoCode = "en"
rtl = false
dateFormat = "2 January 2006"
logo = "ABC.png"

[[params.author.links]]
github = "https://github.com/blackspotinmyiiiies"

[[params.author.links]]
linkedin = "www.linkedin.com/in/danielminthu"

["params.author"]
name = "AskBlueCat"
email = "mthu779@proton.me"
image = "ABC.png"
headline = "AskBlueCat"
bio = "Just a another typical human trying......!"
