[[main]]
none = "none"

[[main]]
name = "writeups"
pre = "blogger"
pageRef = "writeups"
identifier = "2BQ2x8lWFO"
weight = 2

[[main]]
name = "posts"
pre = "hackernews"
pageRef = "posts"
identifier = "yPSyO9PtW6"
weight = 1

[[footer]]
none = "none"
